/**
 * This file is auto-generated by the script.
 * Do not edit this file manually.
 */

import { cn } from "@site/src/utils/twUtils";
import "./font/iconfont.css";

export const RagAcademic = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Academic", className)}
    aria-label="Academic"
    {...restProps}
  />);
};

export const Academic = RagAcademic;

export const RagAgent = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-agent", className)}
    aria-label="agent"
    {...restProps}
  />);
};

export const Agent = RagAgent;

export const RagAgentAi = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-agent-ai", className)}
    aria-label="agent-ai"
    {...restProps}
  />);
};

export const AgentAi = RagAgentAi;

export const RagAgentInvokeFinish = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-tiaoyongchenggongicon", className)}
    aria-label="Agent-invoke finish"
    {...restProps}
  />);
};

export const AgentInvokeFinish = RagAgentInvokeFinish;

export const RagAggregator = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-aggregator", className)}
    aria-label="aggregator"
    {...restProps}
  />);
};

export const Aggregator = RagAggregator;

export const RagAiAgent = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-a-aiagent", className)}
    aria-label="ai agent"
    {...restProps}
  />);
};

export const AiAgent = RagAiAgent;

export const RagAimodels = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-AImoxingshezhi", className)}
    aria-label="aimodels"
    {...restProps}
  />);
};

export const Aimodels = RagAimodels;

export const RagAnthropic = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-anthropic", className)}
    aria-label="anthropic"
    {...restProps}
  />);
};

export const Anthropic = RagAnthropic;

export const RagAriableAssigner = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-a-ariableassigner", className)}
    aria-label="ariable assigner"
    {...restProps}
  />);
};

export const AriableAssigner = RagAriableAssigner;

export const RagAvi = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-avi", className)}
    aria-label="avi"
    {...restProps}
  />);
};

export const Avi = RagAvi;

export const RagAwait = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-await", className)}
    aria-label="await"
    {...restProps}
  />);
};

export const Await = RagAwait;

export const RagAwsBedrock = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-aws-bedrock", className)}
    aria-label="aws-bedrock"
    {...restProps}
  />);
};

export const AwsBedrock = RagAwsBedrock;

export const RagAzure = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-azure", className)}
    aria-label="azure"
    {...restProps}
  />);
};

export const Azure = RagAzure;

export const RagBaichuan13B = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-a-Baichuan13B", className)}
    aria-label="Baichuan 13B"
    {...restProps}
  />);
};

export const Baichuan13B = RagBaichuan13B;

export const RagChat = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-chat", className)}
    aria-label="chat"
    {...restProps}
  />);
};

export const Chat = RagChat;

export const RagClause = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Clause", className)}
    aria-label="Clause"
    {...restProps}
  />);
};

export const Clause = RagClause;

export const RagCodeSet = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-code-set", className)}
    aria-label="code-set"
    {...restProps}
  />);
};

export const CodeSet = RagCodeSet;

export const RagCohere = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-cohere", className)}
    aria-label="cohere"
    {...restProps}
  />);
};

export const Cohere = RagCohere;

export const RagCometapi = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-cometapi", className)}
    aria-label="cometapi"
    {...restProps}
  />);
};

export const Cometapi = RagCometapi;

export const RagCompliance = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Compliance", className)}
    aria-label="Compliance"
    {...restProps}
  />);
};

export const Compliance = RagCompliance;

export const RagCondition = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-condition", className)}
    aria-label="condition"
    {...restProps}
  />);
};

export const Condition = RagCondition;

export const RagContains = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Contains", className)}
    aria-label="Contains"
    {...restProps}
  />);
};

export const Contains = RagContains;

export const RagContentRewrite = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-a-ContentRewrite", className)}
    aria-label="Content Rewrite"
    {...restProps}
  />);
};

export const ContentRewrite = RagContentRewrite;

export const RagContract = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-contract", className)}
    aria-label="contract"
    {...restProps}
  />);
};

export const Contract = RagContract;

export const RagCSV = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-CSV", className)}
    aria-label="CSV"
    {...restProps}
  />);
};

export const CSV = RagCSV;

export const RagCSV1 = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-CSV1", className)}
    aria-label="CSV"
    {...restProps}
  />);
};

export const CSV1 = RagCSV1;

export const RagData = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-data", className)}
    aria-label="data"
    {...restProps}
  />);
};

export const Data = RagData;

export const RagDataflow01 = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-dataflow-01", className)}
    aria-label="dataflow-01"
    {...restProps}
  />);
};

export const Dataflow01 = RagDataflow01;

export const RagDeepinfra = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-deepinfra", className)}
    aria-label="deepinfra"
    {...restProps}
  />);
};

export const Deepinfra = RagDeepinfra;

export const RagDeepseek = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-deepseek", className)}
    aria-label="deepseek"
    {...restProps}
  />);
};

export const Deepseek = RagDeepseek;

export const RagDiscordIconSVGVectorIcon = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-a-DiscordIconSVGVectorIcon", className)}
    aria-label="Discord Icon SVG Vector Icon"
    {...restProps}
  />);
};

export const DiscordIconSVGVectorIcon = RagDiscordIconSVGVectorIcon;

export const RagDiscordFill = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-discord-fill", className)}
    aria-label="discord-fill"
    {...restProps}
  />);
};

export const DiscordFill = RagDiscordFill;

export const RagDoc = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-doc", className)}
    aria-label="doc"
    {...restProps}
  />);
};

export const Doc = RagDoc;

export const RagEqual = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-equal", className)}
    aria-label="equal"
    {...restProps}
  />);
};

export const Equal = RagEqual;

export const RagEquipment = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Equipment", className)}
    aria-label="Equipment"
    {...restProps}
  />);
};

export const Equipment = RagEquipment;

export const RagExcel = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-excel", className)}
    aria-label="excel"
    {...restProps}
  />);
};

export const Excel = RagExcel;

export const RagExecutesql0 = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-executesql-0", className)}
    aria-label="executesql-0"
    {...restProps}
  />);
};

export const Executesql0 = RagExecutesql0;

export const RagFile = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-file", className)}
    aria-label="file"
    {...restProps}
  />);
};

export const File = RagFile;

export const RagFileSub = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-file-sub", className)}
    aria-label="file-sub"
    {...restProps}
  />);
};

export const FileSub = RagFileSub;

export const RagFishaudioBright = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-fishaudio1", className)}
    aria-label="fishaudio-bright"
    {...restProps}
  />);
};

export const FishaudioBright = RagFishaudioBright;

export const RagFishaudioDark = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-a-fishaudiolight", className)}
    aria-label="fishaudio-dark"
    {...restProps}
  />);
};

export const FishaudioDark = RagFishaudioDark;

export const RagGif = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-gif", className)}
    aria-label="gif"
    {...restProps}
  />);
};

export const Gif = RagGif;

export const RagGiteeAI = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-plugin-langgeniusgitee_ai-logo", className)}
    aria-label="GiteeAI"
    {...restProps}
  />);
};

export const GiteeAI = RagGiteeAI;

export const RagGitHub = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-GitHub", className)}
    aria-label="GitHub"
    {...restProps}
  />);
};

export const GitHub = RagGitHub;

export const RagGithubFill = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-github-fill", className)}
    aria-label="github-fill"
    {...restProps}
  />);
};

export const GithubFill = RagGithubFill;

export const RagGoogleCloud = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-google_cloud-icon", className)}
    aria-label="google_cloud"
    {...restProps}
  />);
};

export const GoogleCloud = RagGoogleCloud;

export const RagGpustack = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-gpustack", className)}
    aria-label="gpustack"
    {...restProps}
  />);
};

export const Gpustack = RagGpustack;

export const RagGreaterOrEqual = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Greater-or-equal", className)}
    aria-label="Greater-or-equal"
    {...restProps}
  />);
};

export const GreaterOrEqual = RagGreaterOrEqual;

export const RagGroq = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-plugin-langgeniusgroq-logo", className)}
    aria-label="groq"
    {...restProps}
  />);
};

export const Groq = RagGroq;

export const RagHomework = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-homework", className)}
    aria-label="homework"
    {...restProps}
  />);
};

export const Homework = RagHomework;

export const RagHTTP = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-HTTP", className)}
    aria-label="HTTP"
    {...restProps}
  />);
};

export const HTTP = RagHTTP;

export const RagHttprequest0 = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-httprequest-0", className)}
    aria-label="httprequest-0"
    {...restProps}
  />);
};

export const Httprequest0 = RagHttprequest0;

export const RagHuggingface = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-huggingface_original", className)}
    aria-label="huggingface"
    {...restProps}
  />);
};

export const Huggingface = RagHuggingface;

export const RagIncoming = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Incoming", className)}
    aria-label="Incoming"
    {...restProps}
  />);
};

export const Incoming = RagIncoming;

export const RagJina = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-provider-icon", className)}
    aria-label="Jina"
    {...restProps}
  />);
};

export const Jina = RagJina;

export const RagJpg = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-jpg", className)}
    aria-label="jpg"
    {...restProps}
  />);
};

export const Jpg = RagJpg;

export const RagKnowledgegraph = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-knowledgegraph", className)}
    aria-label="knowledgegraph"
    {...restProps}
  />);
};

export const Knowledgegraph = RagKnowledgegraph;

export const RagKR = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-KR", className)}
    aria-label="KR"
    {...restProps}
  />);
};

export const KR = RagKR;

export const RagKR1 = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-KR1", className)}
    aria-label="KR"
    {...restProps}
  />);
};

export const KR1 = RagKR1;

export const RagLepton = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-lepton", className)}
    aria-label="lepton"
    {...restProps}
  />);
};

export const Lepton = RagLepton;

export const RagLess = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Less", className)}
    aria-label="Less"
    {...restProps}
  />);
};

export const Less = RagLess;

export const RagLessOrEqual = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-less-or-equal", className)}
    aria-label="less-or-equal"
    {...restProps}
  />);
};

export const LessOrEqual = RagLessOrEqual;

export const RagLesson = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Lesson", className)}
    aria-label="Lesson"
    {...restProps}
  />);
};

export const Lesson = RagLesson;

export const RagLinkedin = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-linkedin", className)}
    aria-label="linkedin"
    {...restProps}
  />);
};

export const Linkedin = RagLinkedin;

export const RagListOperations = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-a-listoperations", className)}
    aria-label="list operations"
    {...restProps}
  />);
};

export const ListOperations = RagListOperations;

export const RagListEnd = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-list-end", className)}
    aria-label="list-end"
    {...restProps}
  />);
};

export const ListEnd = RagListEnd;

export const RagListStart = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-list-start", className)}
    aria-label="list-start"
    {...restProps}
  />);
};

export const ListStart = RagListStart;

export const RagLitigation = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-lujingshuli", className)}
    aria-label="Litigation"
    {...restProps}
  />);
};

export const Litigation = RagLitigation;

export const RagLmstudio = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-lmstudio", className)}
    aria-label="lmstudio"
    {...restProps}
  />);
};

export const Lmstudio = RagLmstudio;

export const RagLongcatBright = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-longcat-bright", className)}
    aria-label="longcat-bright"
    {...restProps}
  />);
};

export const LongcatBright = RagLongcatBright;

export const RagLongcatDark = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-longcat-dark", className)}
    aria-label="longcat-dark"
    {...restProps}
  />);
};

export const LongcatDark = RagLongcatDark;

export const RagLoop = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-loop", className)}
    aria-label="loop"
    {...restProps}
  />);
};

export const Loop = RagLoop;

export const RagMcp = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-mcp", className)}
    aria-label="mcp"
    {...restProps}
  />);
};

export const Mcp = RagMcp;

export const RagMd = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-md", className)}
    aria-label="md"
    {...restProps}
  />);
};

export const Md = RagMd;

export const RagMemory = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-memory", className)}
    aria-label="memory"
    {...restProps}
  />);
};

export const Memory = RagMemory;

export const RagMiniMax = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-MiniMax", className)}
    aria-label="MiniMax"
    {...restProps}
  />);
};

export const MiniMax = RagMiniMax;

export const RagMistral = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-mistral-color", className)}
    aria-label="mistral"
    {...restProps}
  />);
};

export const Mistral = RagMistral;

export const RagMkv = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-mkv", className)}
    aria-label="mkv"
    {...restProps}
  />);
};

export const Mkv = RagMkv;

export const RagModelscope = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-modelscope-color", className)}
    aria-label="modelscope"
    {...restProps}
  />);
};

export const Modelscope = RagModelscope;

export const RagMoonshot = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Moonshot", className)}
    aria-label="Moonshot"
    {...restProps}
  />);
};

export const Moonshot = RagMoonshot;

export const RagMore = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-more", className)}
    aria-label="more"
    {...restProps}
  />);
};

export const More = RagMore;

export const RagMp3 = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-icon_MP-", className)}
    aria-label="mp3"
    {...restProps}
  />);
};

export const Mp3 = RagMp3;

export const RagMp4 = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-mp4", className)}
    aria-label="mp4"
    {...restProps}
  />);
};

export const Mp4 = RagMp4;

export const RagNotContains = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-not-contains", className)}
    aria-label="not-contains"
    {...restProps}
  />);
};

export const NotContains = RagNotContains;

export const RagNotEquals = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-not-equals", className)}
    aria-label="not-equals"
    {...restProps}
  />);
};

export const NotEquals = RagNotEquals;

export const RagNovita = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Novita", className)}
    aria-label="Novita"
    {...restProps}
  />);
};

export const Novita = RagNovita;

export const RagNvidia = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-nvidia_", className)}
    aria-label="nvidia_"
    {...restProps}
  />);
};

export const Nvidia = RagNvidia;

export const RagOllama = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-ollama", className)}
    aria-label="ollama"
    {...restProps}
  />);
};

export const Ollama = RagOllama;

export const RagOpenai = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-openai", className)}
    aria-label="openai"
    {...restProps}
  />);
};

export const Openai = RagOpenai;

export const RagOpenAIAPI = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-openai1", className)}
    aria-label="OpenAI-API"
    {...restProps}
  />);
};

export const OpenAIAPI = RagOpenAIAPI;

export const RagOpenRouter = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-OpenRouter", className)}
    aria-label="OpenRouter"
    {...restProps}
  />);
};

export const OpenRouter = RagOpenRouter;

export const RagOthe = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-othe", className)}
    aria-label="othe"
    {...restProps}
  />);
};

export const Othe = RagOthe;

export const RagPdf = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-pdf", className)}
    aria-label="pdf"
    {...restProps}
  />);
};

export const Pdf = RagPdf;

export const RagPerfxcloud1 = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-a-perfxcloud1", className)}
    aria-label="perfxcloud 1"
    {...restProps}
  />);
};

export const Perfxcloud1 = RagPerfxcloud1;

export const RagPersonalized = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Personalized", className)}
    aria-label="Personalized"
    {...restProps}
  />);
};

export const Personalized = RagPersonalized;

export const RagPipeline = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Pipeline", className)}
    aria-label="Pipeline"
    {...restProps}
  />);
};

export const Pipeline = RagPipeline;

export const RagPlay = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-play", className)}
    aria-label="play"
    {...restProps}
  />);
};

export const Play = RagPlay;

export const RagPng = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-png", className)}
    aria-label="png"
    {...restProps}
  />);
};

export const Png = RagPng;

export const RagPost = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-post", className)}
    aria-label="post"
    {...restProps}
  />);
};

export const Post = RagPost;

export const RagPpio = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-ppio", className)}
    aria-label="ppio"
    {...restProps}
  />);
};

export const Ppio = RagPpio;

export const RagPpt = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-ppt", className)}
    aria-label="ppt"
    {...restProps}
  />);
};

export const Ppt = RagPpt;

export const RagPreviewFile = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-a-preview-file", className)}
    aria-label="preview- file"
    {...restProps}
  />);
};

export const PreviewFile = RagPreviewFile;

export const RagProcess = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-process", className)}
    aria-label="process"
    {...restProps}
  />);
};

export const Process = RagProcess;

export const RagPython = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-python", className)}
    aria-label="python"
    {...restProps}
  />);
};

export const Python = RagPython;

export const RagQA = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-QA", className)}
    aria-label="QA"
    {...restProps}
  />);
};

export const QA = RagQA;

export const RagQuality = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Quality", className)}
    aria-label="Quality"
    {...restProps}
  />);
};

export const Quality = RagQuality;

export const RagQuestionClassification = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-a-QuestionClassification", className)}
    aria-label="Question Classification"
    {...restProps}
  />);
};

export const QuestionClassification = RagQuestionClassification;

export const RagRAGFlow = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-RAGFlow", className)}
    aria-label="RAGFlow"
    {...restProps}
  />);
};

export const RAGFlow = RagRAGFlow;

export const RagReparse = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-reparse", className)}
    aria-label="reparse"
    {...restProps}
  />);
};

export const Reparse = RagReparse;

export const RagReplicate = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-AI_Replicate_rengongzhineng", className)}
    aria-label="Replicate"
    {...restProps}
  />);
};

export const Replicate = RagReplicate;

export const RagReply = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-reply", className)}
    aria-label="reply"
    {...restProps}
  />);
};

export const Reply = RagReply;

export const RagResearch = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Research", className)}
    aria-label="Research"
    {...restProps}
  />);
};

export const Research = RagResearch;

export const RagReset = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-reset", className)}
    aria-label="reset"
    {...restProps}
  />);
};

export const Reset = RagReset;

export const RagRetrival0 = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-retrival-0", className)}
    aria-label="retrival-0"
    {...restProps}
  />);
};

export const Retrival0 = RagRetrival0;

export const RagRmvb = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-rmvb", className)}
    aria-label="rmvb"
    {...restProps}
  />);
};

export const Rmvb = RagRmvb;

export const RagRuncode0 = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-runcode-0", className)}
    aria-label="runcode-0"
    {...restProps}
  />);
};

export const Runcode0 = RagRuncode0;

export const RagSales = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Sales", className)}
    aria-label="Sales"
    {...restProps}
  />);
};

export const Sales = RagSales;

export const RagSearch = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-search", className)}
    aria-label="search"
    {...restProps}
  />);
};

export const Search = RagSearch;

export const RagSendemail0 = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-sendemail-0", className)}
    aria-label="sendemail-0"
    {...restProps}
  />);
};

export const Sendemail0 = RagSendemail0;

export const RagSiliconflow = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-plugin-langgeniussiliconflow-logo", className)}
    aria-label="siliconflow"
    {...restProps}
  />);
};

export const Siliconflow = RagSiliconflow;

export const RagSources = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-sources", className)}
    aria-label="sources"
    {...restProps}
  />);
};

export const Sources = RagSources;

export const RagSpeak = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-speak", className)}
    aria-label="speak"
    {...restProps}
  />);
};

export const Speak = RagSpeak;

export const RagSql = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-zu1348", className)}
    aria-label="sql"
    {...restProps}
  />);
};

export const Sql = RagSql;

export const RagSystem = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-system", className)}
    aria-label="system"
    {...restProps}
  />);
};

export const System = RagSystem;

export const RagTencentCloud = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Tencent_Cloud", className)}
    aria-label="Tencent_Cloud"
    {...restProps}
  />);
};

export const TencentCloud = RagTencentCloud;

export const RagTenxunhunyuan = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-tenxunhunyuan", className)}
    aria-label="tenxunhunyuan"
    {...restProps}
  />);
};

export const Tenxunhunyuan = RagTenxunhunyuan;

export const RagTesting = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-testing", className)}
    aria-label="testing"
    {...restProps}
  />);
};

export const Testing = RagTesting;

export const RagText = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-text", className)}
    aria-label="text"
    {...restProps}
  />);
};

export const Text = RagText;

export const RagTextProcessing = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-a-textprocessing", className)}
    aria-label="text processing"
    {...restProps}
  />);
};

export const TextProcessing = RagTextProcessing;

export const RagATextprocessing1 = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-a-textprocessing1", className)}
    aria-label="text processing"
    {...restProps}
  />);
};

export const ATextprocessing1 = RagATextprocessing1;

export const RagTIFF = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-TIFF", className)}
    aria-label="TIFF"
    {...restProps}
  />);
};

export const TIFF = RagTIFF;

export const RagTogetherBright = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-together-bright", className)}
    aria-label="together-bright"
    {...restProps}
  />);
};

export const TogetherBright = RagTogetherBright;

export const RagTogetherDark = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-together-dark", className)}
    aria-label="together-dark"
    {...restProps}
  />);
};

export const TogetherDark = RagTogetherDark;

export const RagTokenpony = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-tokenpony", className)}
    aria-label="tokenpony"
    {...restProps}
  />);
};

export const Tokenpony = RagTokenpony;

export const RagTongyiQianwen = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Tongyi-Qianwen", className)}
    aria-label="Tongyi-Qianwen"
    {...restProps}
  />);
};

export const TongyiQianwen = RagTongyiQianwen;

export const RagTxt = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-txt", className)}
    aria-label="txt"
    {...restProps}
  />);
};

export const Txt = RagTxt;

export const RagUpstage = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-plugin-langgeniusupstage-logo", className)}
    aria-label="upstage"
    {...restProps}
  />);
};

export const Upstage = RagUpstage;

export const RagVllm = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-vllm", className)}
    aria-label="vllm"
    {...restProps}
  />);
};

export const Vllm = RagVllm;

export const RagVolcengine = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Volcengine", className)}
    aria-label="Volcengine"
    {...restProps}
  />);
};

export const Volcengine = RagVolcengine;

export const RagVoyage = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-voyage", className)}
    aria-label="voyage"
    {...restProps}
  />);
};

export const Voyage = RagVoyage;

export const RagWav = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-wav", className)}
    aria-label="wav"
    {...restProps}
  />);
};

export const Wav = RagWav;

export const RagWebcrawler0 = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-webcrawler-0", className)}
    aria-label="webcrawler-0"
    {...restProps}
  />);
};

export const Webcrawler0 = RagWebcrawler0;

export const RagWenxinyiyan = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-wenxinyiyan", className)}
    aria-label="wenxinyiyan"
    {...restProps}
  />);
};

export const Wenxinyiyan = RagWenxinyiyan;

export const RagWord = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-word", className)}
    aria-label="word"
    {...restProps}
  />);
};

export const Word = RagWord;

export const RagX = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-X", className)}
    aria-label="X"
    {...restProps}
  />);
};

export const X = RagX;

export const RagXai = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-xai", className)}
    aria-label="xai"
    {...restProps}
  />);
};

export const Xai = RagXai;

export const RagXinference = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-xinference", className)}
    aria-label="xinference"
    {...restProps}
  />);
};

export const Xinference = RagXinference;

export const RagXls = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-xls", className)}
    aria-label="xls"
    {...restProps}
  />);
};

export const Xls = RagXls;

export const RagXlsx = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-xlsx", className)}
    aria-label="xlsx"
    {...restProps}
  />);
};

export const Xlsx = RagXlsx;

export const RagXunfeixinghuo = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-xunfeixinghuo", className)}
    aria-label="xunfeixinghuo"
    {...restProps}
  />);
};

export const Xunfeixinghuo = RagXunfeixinghuo;

export const RagYoudao = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-youdao", className)}
    aria-label="youdao"
    {...restProps}
  />);
};

export const Youdao = RagYoudao;

export const RagYoutube = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-Youtube", className)}
    aria-label="Youtube"
    {...restProps}
  />);
};

export const Youtube = RagYoutube;

export const RagZhipuai = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {
  return (<i
    className={cn("icon-zhipuai", className)}
    aria-label="zhipuai"
    {...restProps}
  />);
};

export const Zhipuai = RagZhipuai;
