import path from 'node:path';
import fs from 'node:fs';

import { startCase } from 'lodash-es';

const pascalCase = (str) => startCase(str).replace(/ +/g, '');

const [target] = process.argv.slice(2);

if (!target) {
  console.error('Target is required');
  process.exit(1);
}

const PROJECT_ROOT = path.resolve(import.meta.dirname, '..');
const TARGET_ROOT = path.resolve(PROJECT_ROOT, target);

const fontJsonFilePath = path.resolve(TARGET_ROOT, './font/iconfont.json');
const fontJsonFile = JSON.parse(fs.readFileSync(fontJsonFilePath, 'utf8'));

const fontPrefix = pascalCase(fontJsonFile.name);
const glyphs = fontJsonFile.glyphs;

const generatedNameSet = new Set();
const glyphsCodeLines = [
  `/**`,
  ` * This file is auto-generated by the script.`,
  ` * Do not edit this file manually.`,
  ` */`,
  ``,
  `import { cn } from "@site/src/utils/twUtils";`,
  `import "./font/iconfont.css";`,
  ``,
  ...glyphs
    .filter(glyph => /^[a-zA-Z][- \w]*$/.test(glyph.name))
    .sort((a, b) => a.name.localeCompare(b.name) || a.font_class.localeCompare(b.font_class))
    .flatMap((glyph) => {
      const _name = pascalCase(glyph.name);
      const _fontClass = pascalCase(glyph.font_class);
      const glyphName = (generatedNameSet.has(_name) ? _fontClass : _name);

      // Respect icon's name in `iconfont.json`
      // do not generate if duplicated
      if (generatedNameSet.has(glyphName)) {
        return '';
      }

      generatedNameSet.add(glyphName);
      const prefixedGlyphName = `${fontPrefix}${glyphName}`;

      return [
        `export const ${prefixedGlyphName} = ({ className, ...restProps }: React.HTMLAttributes<HTMLElement>) => {`,
        `  return (<i`,
        `    className={cn("icon-${glyph.font_class}", className)}`,
        `    aria-label="${glyph.name}"`,
        `    {...restProps}`,
        `  />);`,
        `};`,
        ``,
        `export const ${glyphName} = ${prefixedGlyphName};`,
        ``,
      ].join('\n');
    }),
];

const glyphsCode = glyphsCodeLines.join('\n');

const indexFilePath = path.resolve(TARGET_ROOT, './index.tsx');
const indexFile = fs.writeFileSync(indexFilePath, glyphsCode);